version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql+psycopg2://postgres:123456@db:5432/postsanamed

      - SECRET_KEY=tu_secreto_aqui
      - MAIL_USERNAME=sanamed467@gmail.com
      - MAIL_PASSWORD=bkca lkuj cahk rnlm
        - LANG=C.UTF-8

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postsanamed
    ports:
      - "5433:5432"  # Cambiar el 5432 externo por 5433